# This is a basic workflow that is manually triggered

name: html to pdf workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Action to clone your repository into the GitHub runner. This step replaces the git clone command 
    - name: Checkout repository
      uses: actions/checkout@v3

    # Action to set up a Python environment. Specify the Python version you need (e.g., 3.9 or 3.x for the latest version).
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Installs the Python dependencies listed in your requirements.txt file using pip
    - name: Install dependencies
      run: |
        cd html-pdf-converter/
        pip install -r requirements.txt

    # Executes a Python script
    - name: Run Python script
      run: |
        cd html-pdf-converter/
        python3 html-pdf-converter-email.py
    # Passes secrets as environment variables to Python script  
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}